version: 0.0
os: linux

files:
  - source: /  # 로컬에서 배포할 파일들
    destination: /home/ec2-user/aws-study
    file_exists_behavior: OVERWRITE  # 파일이 존재할 경우 덮어쓰기

permissions:
  - object: /home/ec2-user/aws-study
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/after_install.sh  # 애플리케이션 시작을 위한 스크립트
      timeout: 300
      runas: ec2-user
