version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/builds
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/builds
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755  # 실행 권한 부여

hooks:
  AfterInstall:  
    - location: aws-study/scripts/deploy.sh
      timeout: 300
      runas: ec2-user
