version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/aws-study
    file_exists_behavior: OVERWRITE  # ✅ 올바른 위치로 이동

permissions:
  - object: /home/ec2-user/aws-study
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh  # ✅ 기존 파일 삭제를 위한 스크립트
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/after_install.sh  # ✅ 애플리케이션 시작을 위한 스크립트
      timeout: 300
      runas: ec2-user

