version: 0.0
os: linux

files:
  - source: / 
    destination: /home/ec2-user/aws-study
file_exists_behavior: OVERWRITE  # 파일이 존재할 경우 덮어쓰기

permissions:
  - object: /home/ec2-user/aws-study
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: hellogsm-server-2/scripts/after_install.sh
      timeout: 300
      runas: ec2-user
