name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List files to verify Dockerfile exists
      run: |
        ls -al
        if [ ! -f my-django-app/Dockerfile ]; then
          echo "Dockerfile not found!"
          exit 1
        fi

    - name: Build and tag the Docker image
      run: |
        timestamp=$(date +%s)
        docker build . --file my-django-app/Dockerfile --tag my-django-app:$timestamp
        docker tag my-django-app:$timestamp my-dockerhub-username/my-django-app:latest
        docker tag my-django-app:$timestamp my-dockerhub-username/my-django-app:$timestamp

    - name: Log in to Docker Hub
      run: |
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Push the Docker image to Docker Hub
      run: |
        docker push my-dockerhub-username/my-django-app:latest
        docker push my-dockerhub-username/my-django-app:$timestamp
